/*
 *  (c) Copyright 2016-2017 Hewlett Packard Enterprise Development Company LP.
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU Lesser General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU Lesser General Public License for more details.
 *
 *  You should have received a copy of the GNU Lesser General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 *  As an exception, the copyright holders of this Library grant you permission
 *  to (i) compile an Application with the Library, and (ii) distribute the
 *  Application containing code generated by the Library and added to the
 *  Application during this compilation process under terms of your choice,
 *  provided you also meet the terms and conditions of the Application license.
 *
 */

#ifndef _NVS_MEMORY_MANAGER_H_
#define _NVS_MEMORY_MANAGER_H_

#include <memory>
#include <atomic>
#include <mutex>
#include <sheap/log.h>
#include "global_ptr.h"


namespace nvs{

    class MemoryManager
    {
    public:

        static MemoryManager *GetInstance();

        void *GlobalToLocal(GlobalPtr ptr);
        GlobalPtr LocalToGlobal(void *addr);
        ErrorCode CreateLog(PoolId id, size_t shelf_size);

        ErrorCode DestroyLog(PoolId id);

        ErrorCode FindLog(PoolId id, Log **log);

        Log *FindLog(PoolId id);

    private:
        static std::atomic<MemoryManager*> instance_;
        static std::mutex mutex_;

        MemoryManager();
        ~MemoryManager();

        class Impl_;
        std::unique_ptr<Impl_> pimpl_;

    };
} // namespace nvs
#endif
